version: "3.8"

services:
  master-db:
    build:
      context: .
      dockerfile: Dockerfile
      target: master
    environment:
      # MySQL Master environment variables
      MYSQL_ROOT_PASSWORD: ${MASTER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MASTER_MYSQL_DATABASE}
      MYSQL_USER: ${MASTER_MYSQL_USER}
      MYSQL_PASSWORD: ${MASTER_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MASTER_MYSQL_ALLOW_EMPTY_PASSWORD}
    hostname: master-db
    container_name: master-db
    ports:
      - "3300:3306"  # Map host port 3300 to container port 3306
    networks:
      - replica-net
    # volumes:
    #   - ./master/data:/var/lib/mysql  # Mount volume for persistent data if required

  read-replica:
    build:
      context: .
      dockerfile: Dockerfile
      target: slave
    environment:
      # MySQL Read Replica environment variables
      MYSQL_ROOT_PASSWORD: ${SLAVE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SLAVE_MYSQL_DATABASE}
      MYSQL_USER: ${SLAVE_MYSQL_USER}
      MYSQL_PASSWORD: ${SLAVE_MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${SLAVE_MYSQL_ALLOW_EMPTY_PASSWORD}
    hostname: read-replica
    container_name: read-replica
    ports:
      - "3301:3306"  # Map host port 3301 to container port 3306
    networks:
      - replica-net
    # volumes:
    #   - ./read-replica/data:/var/lib/mysql  # Mount volume for persistent data if required


networks:
  replica-net:
    name: replica-net  # Define a custom network for communication between services
